from pydantic import BaseModel, ConfigDict


# ------------------------------------------------------------------
# SHARED BASE SCHEMA
# ------------------------------------------------------------------
class TeamBase(BaseModel):
    """
    Shared properties for Team schemas (used for both creation and reading).
    """
    conference: str
    division: str
    city: str
    name: str
    full_name: str
    abbreviation: str


# ------------------------------------------------------------------
# CREATION SCHEMA (INPUT)
# ------------------------------------------------------------------
class TeamCreate(TeamBase):
    """
    Schema for creating a new team.
    ID is excluded because it is auto-generated by the database.
    """
    pass


# ------------------------------------------------------------------
# RESPONSE SCHEMA (OUTPUT)
# ------------------------------------------------------------------
class TeamResponse(TeamBase):
    """
    Schema for returning team data.
    Includes the DB-generated ID.
    """
    id: int

    # Configuration to allow Pydantic to read data from SQLAlchemy models
    model_config = ConfigDict(from_attributes=True)
